# Application Configuration
spring:
  application:
    name: var-calculator

  # Database Configuration
  datasource:
    url: jdbc:postgresql://localhost:5432/var_calculator
    username: var_user
    password: var_password
    driver-class-name: org.postgresql.Driver
    hikari:
      maximum-pool-size: 20
      minimum-idle: 5
      connection-timeout: 30000
      idle-timeout: 600000
      max-lifetime: 1800000

  # JPA Configuration
  jpa:
    hibernate:
      ddl-auto: validate
    show-sql: false
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect
        format_sql: true
        jdbc:
          batch_size: 50
        order_inserts: true
        order_updates: true

  # Flyway Configuration
  flyway:
    enabled: true
    locations: classpath:db/migration
    baseline-on-migrate: true
    validate-on-migrate: true

  # File Upload Configuration
  servlet:
    multipart:
      max-file-size: 50MB
      max-request-size: 50MB

  # Jackson Configuration
  jackson:
    serialization:
      write-dates-as-timestamps: false
    deserialization:
      fail-on-unknown-properties: false

# Server Configuration
server:
  port: 8080
  servlet:
    context-path: /api

# Management/Actuator Configuration
management:
  endpoints:
    web:
      exposure:
        include: health,info,metrics,prometheus
  endpoint:
    health:
      show-details: always

# Application Specific Configuration
var-calculator:
  # VaR Calculation Settings
  var:
    default-confidence-levels: [0.95, 0.99]
    default-window-size: 252 # Trading days in a year
    monte-carlo-simulations: 10000

  # Price Data Settings
  price-data:
    default-provider: alpha-vantage
    alpha-vantage:
      api-key: ${ALPHA_VANTAGE_API_KEY:demo}
      base-url: https://www.alphavantage.co/query
      rate-limit-per-minute: 5

  # Reporting Settings
  reports:
    output-directory: ${java.io.tmpdir}/var-reports
    retention-days: 30

  # Scheduling Settings
  scheduler:
    daily-var-calculation:
      enabled: true
      cron: "0 0 6 * * MON-FRI" # 6 AM on weekdays
      timezone: "America/New_York"

# Logging Configuration
logging:
  level:
    com.riskmanagement.varcalculator: INFO
    org.springframework.web: DEBUG
    org.hibernate.SQL: DEBUG
    org.hibernate.type.descriptor.sql.BasicBinder: TRACE
  pattern:
    console: "%d{yyyy-MM-dd HH:mm:ss} - %msg%n"
    file: "%d{yyyy-MM-dd HH:mm:ss} [%thread] %-5level %logger{36} - %msg%n"
  file:
    name: logs/var-calculator.log
